version: 2
registries:
  npm-github:
    type: npm-registry
    url: https://npm.pkg.github.com
    token: ${{ secrets.NPM_READ_PACKAGES }}
updates:
  - package-ecosystem: "gomod"
    directory: "/"
    open-pull-requests-limit: 10
    schedule:
      interval: daily
    groups:
      gomod-dependencies:
        update-types:
        - "minor"
        - "patch"
  - package-ecosystem: "npm"
    directory: "/"
    registries:
      - npm-github
    schedule:
      interval: daily
    groups:
      npm-dependencies:
        update-types:
        - "minor"
        - "patch"
  - package-ecosystem: "github-actions"
    directory: "/"
    schedule:
      interval: daily
    groups:
      github-actions-dependencies:
        update-types:
        - "minor"
        - "patch"
  - package-ecosystem: "pip"
    directories:
      - "/"
      - "/.devcontainer"
    schedule:
      interval: daily
    ignore:
      - dependency-name: "elasticsearch"
  - package-ecosystem: "docker"
    directory: "/deployments"
    schedule:
      interval: daily
    groups:
      docker-dependencies:
        update-types:
        - "minor"
        - "patch"
  # this one was originally added for recaptcha-password-check:
  - package-ecosystem: "maven"
    directory: "/"
    schedule:
      interval: daily
    groups:
      pip-dependencies:
        update-types:
        - "minor"
        - "patch"
