name: linter
on:
  pull_request:
    branches: [ main ]

jobs:
  linter:
    name: lint
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
        with:
          persist-credentials: false

      - uses: actions/setup-python@v5
        with:
          python-version: 3.12

      - name: Install uv
        run: curl -LsSf https://astral.sh/uv/install.sh | sh

      # - name: Add uv to PATH
      #   run: echo "$HOME/.local/bin" >> $GITHUB_PATH

      # - name: Install dependencies
      #   run: uv sync --group dev

      - name: Check __init__.py in folders
        run: uv run python check_init_files.py

      - name: Run Linter
        run: |
          uv run find . -name '*.py' -not -path './.venv/*' -print | xargs uv run pylint
