name: "pr-title"

on:
  pull_request:
    branches: [main]
    types: [opened, edited, synchronize, reopened]

jobs:
  check-title:
    runs-on: ubuntu-latest
    timeout-minutes: 1
    permissions:
      pull-requests: read
    steps:
      - name: Pull Request title rules
        uses: deepakputhraya/action-pr-title@master
        with:
          regex: '^(\[EXRATE-\d+\]:).*'
